# Generated by Django 4.1.4 on 2023-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_customer_remove_products_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="items",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="products",
            name="order_status",
            field=models.BooleanField(default=False),
        ),
    ]
