# Generated by Django 4.1.3 on 2022-12-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGraphy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('FoodChoice', models.CharField(choices=[('Wedding', 'Wedding'), ('Ear-Boring', 'Ear-Boring'), ('BirthDay', 'BirthDay'), ('PhotoShoot', 'PhotoShoot'), ('Celebrations', 'Celebrations'), ('Others', 'Others')], max_length=50)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
