# Generated by Django 4.1.3 on 2022-12-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photography',
            old_name='FoodChoice',
            new_name='service',
        ),
    ]
