# Generated by Django 4.1.3 on 2022-12-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='shirt_size',
            new_name='FoodChoice',
        ),
    ]
