# Generated by Django 4.1.4 on 2023-09-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_alter_foods_foodchoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="foods",
            name="items",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="foods",
            name="order_status",
            field=models.BooleanField(default=False),
        ),
    ]
