# Generated by Django 4.1.4 on 2022-12-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_remove_project_syllabus_project_syllabus1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
