# Generated by Django 4.1.4 on 2022-12-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
