# Generated by Django 4.1.4 on 2022-12-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='expertise',
            field=models.CharField(max_length=50),
        ),
    ]
