# Generated by Django 4.1.4 on 2022-12-18 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_rename_courses_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
