# Generated by Django 4.1.4 on 2022-12-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='college_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
