# Generated by Django 4.1.4 on 2023-01-04 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_contact_college_name_contact_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='msg',
            new_name='message',
        ),
    ]
